### ISSUE TITLE
XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 45924508816 bytes.

### ISSUE THREAD

**Issue by KelvinTao** [dattalab/keypoint-moseq#247]
Hello, 
    When I run    Fitting the full model part on NVIDIA  RTX 3090 GPU (24 GB)
         # run fitting for an additional 500 iters
            model = kpms.fit_model(
                model,
                data,
                metadata,
                project_dir,
                model_name,
                ar_only=False,
                start_iter=current_iter,
                num_iters=current_iter + 500,
            )[0]

I get the problem:

---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
File /DATA/taoxianming/rat/solo_script/keypoint-moseq/kpms_test.py:[2](https://vscode-remote+ssh-002dremote-002blilab3090.vscode-resource.vscode-cdn.net/DATA/taoxianming/rat/solo_script/keypoint-moseq/kpms_test.py:2)
      1 for epoch in range(1):
----> 2     model, model_name = kpms.fit_model(model,data,metadata,project_dir,model_name,ar_only=False,
      3         start_iter=current_iter,num_iters=current_iter + 5,)[0]

File ~/.conda/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/fitting.py:253, in fit_model(model, data, metadata, project_dir, model_name, num_iters, start_iter, verbose, ar_only, parallel_message_passing, jitter, generate_progress_plots, save_every_n_iters, location_aware, **kwargs)
    251 for iteration in pbar:
    252     try:
--> [253](https://vscode-remote+ssh-002dremote-002blilab3090.vscode-resource.vscode-cdn.net/DATA/taoxianming/rat/solo_script/~/.conda/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/fitting.py:253)         model = _wrapped_resample(
    254             resample_func,
    255             data,
    256             model,
    257             pbar=pbar,
    258             ar_only=ar_only,
    259             verbose=verbose,
    260             jitter=jitter,
    261             parallel_message_passing=parallel_message_passing,
    262         )
    263     except StopResampling:
    264         break

File ~/.conda/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/fitting.py:25, in _wrapped_resample(resample_func, data, model, pbar, **resample_options)
     23 def _wrapped_resample(resample_func, data, model, pbar=None, **resample_options):
...
-> [1306](https://vscode-remote+ssh-002dremote-002blilab3090.vscode-resource.vscode-cdn.net/DATA/taoxianming/rat/solo_script/~/.conda/envs/keypoint_moseq/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py:1306)   results = self.xla_executable.execute_sharded(input_bufs)
   1308 if dispatch.needs_check_special():
   1309   out_arrays = results.disassemble_into_single_device_arrays()

XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 45924508816 bytes. 

How to solve this problem? Is the data or model too big ?

**Comment by JRJacoby** [comment]
See our docs on manging memory. If that doesn't work for you, let us know what you've tried and we can try to assist:

https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#out-of-memory

**Comment by KelvinTao** [comment]
I solved the problem by using less data. It seems that kpms generate many folds of original data while analyzing.

**Comment by JRJacoby** [comment]
Yeah we estimate in the docs roughly 3MB/100frames when using latent_dim=4.

**Comment by KelvinTao** [comment]
Thank you. I'll try other methods for Bigger data, multi-GPU or split data before training.
